/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Savvin (https://sketchfab.com/savvin)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/a3-greek-parthenon-fffbe109e51e4382a1119528b77eb704
title: A3 Greek Parthenon
*/

import React, {useRef} from 'react';
import {useGLTF} from '@react-three/drei';
import {TextureLoader} from 'three';

export default function Temple() {
	const {nodes, materials} = useGLTF('/3dModels/Temple.glb');
	const texture = new TextureLoader().load('/textures/white-stone.jpeg'); // Add texture

	materials.lambert1.map = texture; // Change model texture to the new one

	return (
		<group scale={10} position={[3, 0, -2.2]} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
					<group position={[3.73, 23.41, -18.29]} scale={[0.26, 0.41, 0.5]}>
						<mesh castShadow receiveShadow geometry={nodes.pCube13_lambert1_0.geometry} material={materials.lambert1} />
					</group>
					<group position={[25.75, 23.26, -3.71]} rotation={[0, -Math.PI / 2, 0]} scale={[0.26, 0.41, 0.78]}>
						<mesh castShadow receiveShadow geometry={nodes.pCube15_lambert1_0.geometry} material={materials.lambert1} />
					</group>
					<group position={[25.75, 23.26, 37.52]} rotation={[0, -Math.PI / 2, 0]} scale={[0.26, 0.41, 0.78]}>
						<mesh castShadow receiveShadow geometry={nodes.pCube12_lambert1_0.geometry} material={materials.lambert1} />
					</group>
					<group position={[-29.09, 45.78, 5.86]} scale={18.8}>
						<mesh castShadow receiveShadow geometry={nodes.pCube1_lambert1_0.geometry} material={materials.lambert1} />
					</group>
					<group position={[-61.84, 23.41, -18.29]} scale={[0.26, 0.41, 0.5]}>
						<mesh castShadow receiveShadow geometry={nodes.pCube14_lambert1_0.geometry} material={materials.lambert1} />
					</group>
					<group position={[0.08, 0, 33.83]}>
						<mesh castShadow receiveShadow geometry={nodes.entire_pillar6_lambert1_0.geometry} material={materials.lambert1} />
					</group>
					<mesh castShadow receiveShadow geometry={nodes.entire_pillar_lambert1_0.geometry} material={materials.lambert1} />
					<group position={[-29.45, 0, 0]}>
						<mesh castShadow receiveShadow geometry={nodes.entire_pillar1_lambert1_0.geometry} material={materials.lambert1} />
					</group>
					<group position={[-58.14, 0, 0]}>
						<mesh castShadow receiveShadow geometry={nodes.entire_pillar2_lambert1_0.geometry} material={materials.lambert1} />
					</group>
					<group position={[-58.14, 0, 18.18]}>
						<mesh castShadow receiveShadow geometry={nodes.entire_pillar3_lambert1_0.geometry} material={materials.lambert1} />
					</group>
					<group position={[0.08, 0, 16.54]}>
						<mesh castShadow receiveShadow geometry={nodes.entire_pillar7_lambert1_0.geometry} material={materials.lambert1} />
					</group>
					<group position={[-58.14, 0, 33.83]}>
						<mesh castShadow receiveShadow geometry={nodes.entire_pillar4_lambert1_0.geometry} material={materials.lambert1} />
					</group>
					<group position={[-28.85, 0, 33.83]}>
						<mesh castShadow receiveShadow geometry={nodes.entire_pillar5_lambert1_0.geometry} material={materials.lambert1} />
					</group>
					<group position={[-19.02, -2.61, 15.12]} rotation={[0, -Math.PI / 2, 0]} scale={[0.09, 0.14, 0.14]}>
						<mesh castShadow receiveShadow geometry={nodes.pCube17_lambert1_0.geometry} material={materials.lambert1} />
					</group>
					<group position={[-19.02, -2.61, 18.15]} rotation={[0, -Math.PI / 2, 0]} scale={[0.09, 0.14, 0.14]}>
						<mesh castShadow receiveShadow geometry={nodes.pCube18_lambert1_0.geometry} material={materials.lambert1} />
					</group>
					<group position={[-29.3, -0.73, 16.94]} scale={[61.85, 5.18, 42.79]}>
						<mesh castShadow receiveShadow geometry={nodes.stairs_base_lambert1_0.geometry} material={materials.lambert1} />
					</group>
					<mesh castShadow receiveShadow geometry={nodes.nurbsToPoly1_lambert1_0.geometry} material={materials.lambert1} />
					<mesh castShadow receiveShadow geometry={nodes.nurbsToPoly2_lambert1_0.geometry} material={materials.lambert1} />
					<mesh castShadow receiveShadow geometry={nodes.nurbsToPoly3_lambert1_0.geometry} material={materials.lambert1} />
					<mesh castShadow receiveShadow geometry={nodes.nurbsToPoly4_lambert1_0.geometry} material={materials.lambert1} />
					<mesh castShadow receiveShadow geometry={nodes.nurbsToPoly5_lambert1_0.geometry} material={materials.lambert1} />
					<mesh castShadow receiveShadow geometry={nodes.nurbsToPoly6_lambert1_0.geometry} material={materials.lambert1} />
					<mesh castShadow receiveShadow geometry={nodes.nurbsToPoly7_lambert1_0.geometry} material={materials.lambert1} />
					<mesh castShadow receiveShadow geometry={nodes.nurbsToPoly8_lambert1_0.geometry} material={materials.lambert1} />
					<group position={[-28.73, 1.74, 16.63]} scale={[11.39, 3.09, 3.09]}>
						<mesh castShadow receiveShadow geometry={nodes.pCube16_lambert1_0.geometry} material={materials.lambert1} />
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload('/3dModels/Temple.glb');
